# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
                    formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

## Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: true
#    bundles:        [ ]
#    #java: /usr/bin/java
#    node: /usr/bin/node
#    node_paths: ["%kernel.root_dir%/../node_modules"]
#    write_to: "%kernel.root_dir%/../web/compiled"
#    filters:
#        less:
#            apply_to: "\.less$"
#        cssrewrite: ~
#
#    assets:
#        bootstrap_css:
#            inputs:
#                - %kernel.root_dir%/../web/bower/bootstrap/dist/css/bootstrap.css
#            filters:
#                - cssrewrite
#            output: css/bootstrap.css
#        global_css:
#            inputs:
#                - %kernel.root_dir%/../web/less/site.less
#            filters:
#                - less
#                - cssrewrite
#            output: css/global.css
#        catalog_css:
#            inputs:
#                - %kernel.root_dir%/../web/less/catalog.less
#            filters:
#                - less
#                - cssrewrite
#            output: css/catalog.css
#        vendor_js:
#            inputs:
#                - %kernel.root_dir%/../web/bower/jquery/dist/jquery.js
#                - %kernel.root_dir%/../web/bower/bootstrap/dist/js/bootstrap.js
#                - %kernel.root_dir%/../web/bower/angular/angular.js
#            output: js/bootstrap.js
#        global_js:
#            input:
#                - @vendor_js
#                - %kernel.root_dir%/../web/js/site/header.js
#            output: js/global.js